name = "EdgarXBRL"
uuid = "b672df55-be7f-465c-b1c4-0f0aeb52051d"
authors = ["Mario Milone"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
